Acco_Manag_Project/Acco_Manag_Project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}),
    path('admin/', admin.site.urls, name="admin"),
    path('home/', include('General.urls')),
    path('contabilidad_general/', include('Contabilidad_General.urls')),
    path('form_agregar_balance/', include('Contabilidad_General.urls2')),
    path('balance_general/', include('Balance_General.urls')),
    path('form_balance_general/', include('Balance_General.urls2')),
    path('cuentas_cobrar/', include('Cuentas_Cobrar.urls')),
    path('form_nueva_factura/', include('Cuentas_Cobrar.urls2')),
    path('editar_cuenta_cobrar/', include('Cuentas_Cobrar.urls3')),
    path('cuentas_pagar/', include('Cuentas_Pagar.urls')),
    path('form_nueva_factura_pagar/', include('Cuentas_Pagar.urls2')),
    path('activos_fijos/', include('Activos_Fijos.urls')),
    path('form_activo_fijo/', include('Activos_Fijos.urls2')),
    path('periodos/', include('Periodos.urls')),
    path('editar_periodo/', include('Periodos.urls2')),
    path('banco/', include('Banco.urls')),
    path('form_nuevo_recibo/', include('Banco.urls2')),
    path('nominas/', include('Nominas.urls')),
    path('form_nomina/', include('Nominas.urls2')),
    path('editar_nomina/', include('Nominas.urls3')),
    path('', include('Login.urls')),
    path('recuperar-contrasena/', include('Login.urls2')),
    path('cuentas_bancarias/', include('Cuenta_Bancaria.urls')),
    path('editar_cuenta_bancaria/', include('Cuenta_Bancaria.urls2')),

]

Acco_Manag_Project/Banco/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.banco, name="banco"),
    path('clientesList',views.clientesListados, name="clientesList"),
    path('eliminar_banco/<id>',views.eliminar_banco, name="Eliminar_Banco"),
    path('edicion_banco/<id>',views.edicion_banco, name="Edicion_Banco"),
    path('edicion_banco/editar_banco/<id>',views.editar_banco)      
]

Acco_Manag_Project/Banco/models.py
from django.db import models
from Periodos.models import Periodo
from Nominas.models import Compania, Departamento, TipoCedula
from Login.models import Rol
from django.contrib.auth.models import User

# Create your models here.

class Banco(models.Model):
  IdDepartamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
  Codigo = models.CharField(max_length=20)
  Estado =models.BooleanField()  

  def __str__(self):
        return self.Codigo

Acco_Manag_Project/Nominas/models.py
from django.db import models
from Periodos.models import Periodo
from Login.models import Rol
from django.contrib.auth.models import User
# Create your models here.

class Puesto(models.Model):
  puesto = models.CharField(max_length=50)
  descripcion = models.TextField()

  def __str__(self):
        return self.puesto


class TipoBeneficio(models.Model):
  TipoBeneficio = models.CharField(max_length=50)
  Descripcion = models.TextField()

  def __str__(self):
        return self.TipoBeneficio

class TipoCedula(models.Model):
  TipoCedula = models.CharField(max_length=50, unique=True)
  Descripcion = models.TextField()

  def __str__(self):
        return self.TipoCedula

class Empleado(models.Model):
  puestos = []
  for i in range(5):
    f = lambda j, i = i : i
    puestos.append(f)
  
  Nombre = models.CharField(max_length=50)
  PrimerApellido = models.CharField(max_length=50, verbose_name="Primer Apellido")
  SegundoApellido = models.CharField(max_length=50, verbose_name="Segundo Apellido")
  TipoCedula = models.ForeignKey(TipoCedula, on_delete=models.CASCADE, blank=True, null=True, verbose_name="Tipo de Cédula")
  Cedula =models.CharField(max_length=50, verbose_name="Cédula")
  Direccion = models.TextField(verbose_name="Dirección")
  Telefono = models.CharField(max_length=20, verbose_name="Teléfono")
  FechaIngreso = models.DateField(verbose_name="Fecha de Ingreso")
  Salario = models.FloatField()
  IdTipoBeneficio = models.ForeignKey(TipoBeneficio, on_delete=models.CASCADE,verbose_name="Tipo de Beneficio")
  SaldoVacaciones = models.CharField(max_length=30, verbose_name="Saldo Vacaciones")
  BonoAnual = models.FloatField(verbose_name="Bono Anual")
  IdPuesto = models.ForeignKey(Puesto, on_delete=models.CASCADE, verbose_name="Puesto")
  IdUsuario = models.OneToOneField(User, on_delete=models.CASCADE,default=None, verbose_name="Usuario")
  IdRol = models.ForeignKey(Rol, on_delete=models.CASCADE, verbose_name="Rol")

  def __str__(self):
        return self.Nombre

class TipoCliente(models.Model):
  TipoCliente= models.CharField(max_length=30)
  
  def __str__(self):
        return self.TipoCliente

class Cliente(models.Model):
  NombreCompleto = models.CharField(max_length=100, verbose_name="Nombre Completo")
  TipoCedula= models.ForeignKey(TipoCedula, on_delete= models.CASCADE, blank=True, null=True, verbose_name="Tipo de Cédula")
  Cedula = models.CharField(max_length=50, verbose_name="Cédula")
  Direccion = models.TextField(verbose_name="Dirección")
  RazonSocial= models.TextField(verbose_name="Razón Social")
  E_Mail = models.CharField(max_length=50, verbose_name="Correo")
  IdTipoCliente= models.ForeignKey(TipoCliente,on_delete=models.CASCADE, verbose_name="Tipo de Cliente")
  IdUsuario = models.OneToOneField(User,on_delete=models.CASCADE, verbose_name="Usuario")
  IdRol=models.ForeignKey(Rol,on_delete=models.CASCADE, verbose_name="Rol")

  def __str__(self):
        return self.NombreCompleto

class Compania(models.Model):
  Nombre = models.CharField(max_length=50)
  Direccion = models.TextField()
  Telefono = models.CharField(max_length=20)
  E_mail = models.CharField(max_length=50)
  tipoCedula = models.ForeignKey(TipoCedula,on_delete=models.CASCADE,default=None,null=False, blank=False)
  Cedula= models.CharField(max_length= 50)
  IdCliente = models.ManyToManyField(Cliente)
  
  def __str__(self):
        return self.Nombre
  
class Departamento(models.Model):
  Codigo = models.CharField(max_length=20)
  Departamento = models.CharField(max_length=50)
  Capacidad = models.IntegerField()
  Costo= models.FloatField()
  def __str__(self):
        return self.Departamento

class Nomina(models.Model):
  IdPeriodo = models.ForeignKey(Periodo,on_delete=models.CASCADE)
  IdCompania = models.ForeignKey(Compania,on_delete=models.CASCADE)
  IdEmpleado = models.OneToOneField(Empleado,on_delete=models.CASCADE)
  IdDepartamento= models.ForeignKey(Departamento,on_delete=models.CASCADE)
  Monto = models.FloatField()
  def __str__(self):
        return self.IdEmpleado.Nombre


  

Acco_Manag_Project/Banco/forms.py
from django import forms
from Nominas.models import Cliente, TipoCliente

class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = [
            'NombreCompleto',
            'TipoCedula',
            'Cedula',
            'Direccion',            
            'RazonSocial',
            'E_Mail',
            'IdTipoCliente',
            'IdRol'
        ]
        widgets = {
             'NombreCompleto': forms.TextInput(attrs={'class':'form-control'}),            
             'TipoCedula':forms.Select(attrs={'class':'form-control'}),            
            'Cedula':forms.TextInput(attrs={'class':'form-control'}),            
            'Direccion':forms.TextInput(attrs={'class':'form-control'}),
            'RazonSocial':forms.TextInput(attrs={'class':'form-control'}),
            'E_Mail':forms.TextInput(attrs={'class':'form-control'}),              
            'IdTipoCliente':forms.Select(attrs={'class':'form-control'}),       
            'IdRol':forms.Select(attrs={'class':'form-control'})                                              
        }

Acco_Manag_Project/Banco/views.py
import imp
from multiprocessing import context
from django.contrib import messages
from multiprocessing.spawn import import_main_path
from pickle import NONE
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .models import Banco, Departamento, Periodo, Compania
from Nominas.models import Cliente
from .forms import ClienteForm
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
from django.contrib.auth.hashers import make_password
from General.Sender import Sender_Email
from General.views import accion_bitacora
# Create your views here.
def banco(request):
    bancosLista = Banco.objects.all()
    return render(request,"banco.html",{'Bancos':bancosLista})

def clientesListados(request):
    clienteList= Cliente.objects.all()    
    return render(request,"clientesLista.html",{"Clientes": clienteList})

def form_banco(request):
    departamentos= Departamento.objects.all()  
    return render(request,"form_banco.html",{'Departamentos':departamentos})

def registrar_banco(request, *args, **kwargs):   
    departamento = Departamento.objects.get(id=int(request.POST.get('departamento',False)))
    codigo = request.POST.get('codigo',False)    
    estado = request.POST.get('estado',False)  
    Banco.objects.create( IdDepartamento=departamento,Codigo=codigo, Estado=estado)    
    accion_bitacora(request,'Crear Banco','Se ha registrado el banco '+codigo)
    messages.success(request, '¡Banco Agregado!')
    return redirect('/banco')

def eliminar_banco(request, id):
    banco = Banco.objects.get(id=id)
    banco.delete()            
    accion_bitacora(request,'Eliminar Banco','Se ha eliminado el banco '+banco.Codigo)
    messages.success(request, '¡Banco Eliminado!')
    return redirect('/banco')

def edicion_banco(request, id):
    banco = Banco.objects.get(id=id)
    departamentosListados = Departamento.objects.all()
    return render(request,'editar_banco.html', {'Banco':banco,"Departamentos":departamentosListados,'id':id})

def editar_banco(request, id, *args, **kwargs):   
    departamento = Departamento.objects.get(id=int(request.POST.get('departamento',False)))
    codigo = request.POST.get('codigo',False)    
    estado = request.POST.get('estado',False) 
    banco=Banco.objects.get(id=id)     
    banco.IdDepartamento=departamento
    banco.Codigo=codigo    
    banco.Estado=estado
    banco.save()
    
    accion_bitacora(request,'Modificar Banco','Se ha modificado el banco '+banco.Codigo)
    messages.success(request, '¡Banco Actualizado!')
    return redirect('/banco')

class ClienteCreate(CreateView):
    model = Cliente
    template_name = 'clientes.html'
    form_class = ClienteForm 
    success_url = banco

    def get_context_data(self, **kwargs):
        context = super(ClienteCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():
            cliente = form.save(commit=False)
            nombreCompleto = request.POST.get('NombreCompleto',NONE)            
            cedula = request.POST.get('Cedula',NONE)
            correo = request.POST.get('E_Mail',NONE)
            usuario = nombreCompleto[0:3]+cedula[-4:]
            password = get_random_string(length=12)            
            password_hash = make_password(password)
            cliente.IdUsuario = User.objects.create(username = usuario , password = password_hash,email=correo)
            cliente.save()            
            accion_bitacora(request,'Crear Cliente','Se ha registrado el cliente '+cedula)
            accion_bitacora(request,'Crear Usuario','Se ha registrado el usuario '+usuario)            
            print(password)
            Sender_Email(correo, nombreCompleto,usuario, password)
            clienteList= Cliente.objects.all()
            return redirect("/home")
        else:
            return self.render_to_response(self.get_context_data(form=form),{"Clientes": clienteList})

Acco_Manag_Project/Banco/templates/banco.html
{% extends "base.html" %}

{% block body %}

<main class="col-md-9 ms-sm-auto col-lg-12 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap
    align-items-center pt-3 pb-2 mb-3 border-bottom border-bottom-info">
    <h1 class="h2">Bancos</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
  </div>
  <table class="table" id="table">
    <thead>
      <tr>
        <th>Departamento</th>
        <th>Código</th>
        <th>Estado</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {% for b in Bancos %}
      <tr>
        <td>{{b.IdDepartamento}}</td>
        <td>{{b.Codigo}}</td>
        {% if b.Estado == True %}
        <td>Activo</td>
        {% else %}
        <td>Inactivo</td>
        {% endif %}
        <td> <a href="edicion_banco/{{b.id}}" type="button" class="btn
            btn-warning">Editar </a>          
            <button class="btn btn-danger" role="button" data-toggle="modal" data-target="#confirm-delete-modal" data-url="eliminar_banco/{{b.id}}">Eliminar</button>
          </td>
      </tr>
      {% endfor %}
    </tbody>
    <div class="modal" tabindex="-1" role="dialog" id="confirm-delete-modal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Confirmar eliminación</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>¿Estás seguro de que deseas eliminar el banco?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <a href="#" class="btn btn-danger" id="confirm-delete-btn">Eliminar</a>
          </div>
        </div>
      </div>
    </div>
  </table>
</main>

<script>
  $('#confirm-delete-modal').on('show.bs.modal', function(e) {
    $(this).find('#confirm-delete-btn').attr('href', $(e.relatedTarget).data('url'));
  });
</script>
{% endblock %}

Acco_Manag_Project/Banco/templates/clientes.html
{% extends "base.html" %}

{% block body %}

<main class="col-md-9 ms-sm-auto col-lg-12 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap
    align-items-center pt-3 pb-2 mb-3 border-bottom border-bottom-info">
    <h1 class="h2">Clientes</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
  </div>
  <div>
    <br>
    <br>
    <form method="post">
      <CENTER>
        {% csrf_token%}
        <table class="table" style="width: 80%;">
          {{form.as_table}}
        </table>
        <button type="submit" class="btn btn-success" onclick="activar_notificiacion_nuevo()">Guardar</button>
      </CENTER>
    </form>
  </div>
  <br>
</main>

<script>
  $(document).ready(function(){
    $("#id_TipoCedula").attr("required",true);
  });
</script>

{% endblock %}

Acco_Manag_Project/Banco/templates/clientesLista.html
{% extends "base.html" %}

{% block body %}



<main class="col-md-9 ms-sm-auto col-lg-12 px-md-4" >
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom border-bottom-info">
    <h1 class="h2">Clientes</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
  </div>

  <div>
    <table class="table ">
      <thead >
        <tr>        
           <th>Nombre Completo</th>
           <th>Tipo Cedula</th>
           <th>Cédula</th>
           <th>Dirección</th>
           <th>Razón Social</th>
           <th>Correo</th>
           <th>Tipo Cliente</th>
           <th>Usuario</th>
           <th>Rol</th>
           <th>Acciones</th>
         </tr>
       </thead>
       <tbody>
         {% for c in Clientes%}
            <tr>          
             <td>{{c.NombreCompleto}}</td>
             <td>{{c.TipoCedula}}</td>
             <td>{{c.Cedula}}</td>
             <td>{{c.Direccion}}</td>
             <td>{{c.RazonSocial}}</td>
             <td>{{c.E_Mail}}</td>
             <td>{{c.IdTipoCliente}}</td>
             <td>{{c.IdUsuario}}</td>
             <td>{{c.IdRol}}</td>             
             <td> <a href="editar_estado/{{p.id}}" class="btn btn-dark" role="button">Cerrar Periodo </a></td> 
          </tr>  
         {% endfor %}        
       </tbody>
    </table>

  </main>





{% endblock %}

Acco_Manag_Project/Banco/templates/editar_banco.html
{% extends "base.html" %}

{% block body %}
<main class="col-md-12 ms-sm-auto col-lg-12 px-md-12" >
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom border-bottom-info">
    <h1 class="h2">Banco</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
  </div>
  <center>

    <form action="editar_banco/{{id}}" method="post" style="margin-left: 35%;"> {% csrf_token %}

      
       
      <div class="form-group row">
        <label for="usuario" class="col-2 col-form-label">Departamento</label> 
        <div class="col-4">
          <select id="departamento" name="departamento" class="form-control">            
            <option value="{{ Banco.IdDepartamento.pk }}">{{ Banco.IdDepartamento}}</option>                                 
            {% for d in Departamentos %}
            <option value="{{ d.pk }}">{{ d.Departamento }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="form-group row">
        <label for="usuario" class="col-2 col-form-label">Código</label> 
        <div class="col-4">
          <input value="{{ Banco.Codigo }}" type="text" name="codigo" class="form-control">
        </div>
      </div> 
      <div class="form-group row">
        <label for="estado" class="col-2 col-form-label">Estado</label> 
        <div class="col-4">
          <select id="estado" name="estado" class="form-control">  
            <option value="{{ Banco.Estado }}" >{%if Banco.Estado == True  %} Activo {%else %} Inactivo  {% endif %}</option>selected>      
            {%if Banco.Estado == False %}
            <option value="1">Activo </option>
            {% else %}
            <option value="0">Inactivo</option>
            {%endif%}
          </select>
        </div>
      </div>       
      <div class="form-group row">
        <div class="offset-0 col-8">
          <button type="submit" class="btn btn-success" onclick="activar_notificiacion_editar()">Guardar</button>
        </div>
      </div>
    </center>
  
    </form>
  </main>
{% endblock %}

Acco_Manag_Project/Banco/templates/form_banco.html
{% extends "base.html" %}

{% block body %}
<main class="col-md-9 ms-sm-auto col-lg-12 px-md-4" >
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom border-bottom-info">
    <h1 class="h2">Banco</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
    </div>
  </div>

    <form action="crear_banco" style="margin-left: 25%;" method="post"> {% csrf_token %}
      <center>
      
        
      <div class="form-group row">
        <label for="usuario" class="col-2 col-form-label">Departamento</label> 
        <div class="col-4">
          <select id="departamento" name="departamento" class="form-control" required>   
            <option value="">Seleccione un departamento</option>         
            {% for d in Departamentos %}
            <option value="{{ d.pk }}">{{ d.Departamento }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="form-group row">
        <label for="usuario" class="col-2 col-form-label">Código</label> 
        <div class="col-4">
          <input type="text" placeholder="Digite el código" name="codigo" class="form-control" required>
        </div>
      </div>      
      <div class="form-group row">
        <label for="estado" class="col-2 col-form-label">Estado</label> 
        <div class="col-4">
          
          <select id="estado" name="estado" class="form-control" required>   
            <option value="">Seleccione un estado</option> 
            <option value="1">Activo</option>
            <option value="0">Inactivo</option>
          </select>
        </div>
      </div> 
      <div class="form-group row">
        <div class="offset-0 col-8">

        <button type="submit" class="btn btn-success" onclick="activar_notificiacion_nuevo()">Guardar</button>
        </div>
      </div>
    </center>
     
    </form>
  

  </main>

{% endblock %}